### ISSUE TITLE
Image location

### ISSUE THREAD

**Issue by Stagefright071** [sujaykundu777/devlopr-jekyll#103]
![image](https://user-images.githubusercontent.com/71056504/133575664-7a9da46e-c820-44c9-aee9-eb09dfa4e2d4.png)
Where is this background image (the headphones) located? i want to replace it.
Also, how do i remove the shopping cart?

**Comment by sujaykundu777** [comment]
Hi we have released a update please check this release to help you change the cover image https://devlopr.olvy.co/added-the-ability-to-change-cover-image-easily @Stagefright071  Hope it helps !
