### ISSUE TITLE
Not showing the website properly

### ISSUE THREAD

**Issue by compromyse** [sujaykundu777/devlopr-jekyll#126]
When i run the website using ```bundle exec jekyll serve``` it works properly, but when i push to github, this happens

![image](https://user-images.githubusercontent.com/71056504/142573709-fe45fcfd-e50c-47a0-a3c7-f233f017a379.png)

here is the website: https://compromyse.tk/

**Comment by compromyse** [comment]
Fixed.

**Comment by Zachinquarantine** [comment]
Hi, how did you fix this? I'm having the same problem with my site.

**Comment by compromyse** [comment]
@Zachinquarantine I think reinstalling everything worked. Also, try running `bundle exec jekyll build` and running a simple http server, like a python server with `python3 -m http.server` in the _site folder
