### ISSUE TITLE
Hash sign '#' is added to each page

### ISSUE THREAD

**Issue by andreyka26-git** [sujaykundu777/devlopr-jekyll#187]
Hey guys, I would like to ask why there is hash sign always added to the end of URL and is there any possibility to fix it?
![image](https://user-images.githubusercontent.com/30469229/199127076-02f54dd0-05b5-4a19-8d07-c13f97471d23.png)

**Comment by andreyka26-git** [comment]
The problem was caused by 'snipcart' library. Drop all dependencies related to that library and it will be fixed.

**Comment by MooMooHorse** [comment]
Can you elaborate on how exactly we can "Drop all dependencies related to that library". I tried to comment out all the snip-cart related stuff in _include directory and it's not fixed

**Comment by MooMooHorse** [comment]
Problem solved by commenting out the following parts:
* _include directory
* _layout directory
* _config.yml shop page.

Use `grep -r` in corresponding directories for each occurrence of `snipcart` and comment out corresponding HTML element.

**Comment by andreyka26-git** [comment]
Sorry, was long time ago, I dropped (meaning) I deleted literally files related to it, all configurations, etc, it stopped arising. You could check here it is working: https://andreyka26.com
