### ISSUE TITLE
Font-Awesome CSS Underlines

### ISSUE THREAD

**Issue by adam-stamand** [sujaykundu777/devlopr-jekyll#3]
Issue: The font-awesome icons in the header show an underline when hovered over (See image below).

![Capture](https://user-images.githubusercontent.com/11203314/60761536-8ea27880-9fff-11e9-818e-33e258f3adf3.PNG)

Solution: Add 'text-decoration: none !important;' to the .social-link{} element in devlog.scss. 

I found this solution on SO (https://stackoverflow.com/questions/21983508/strange-underlines-in-font-awesome-css)

**Comment by sujaykundu777** [comment]
Thanks Adam. The issue was resolved :
