### ISSUE TITLE
assets not getting loaded

### ISSUE THREAD

**Issue by Raghwendra-Dey** [sujaykundu777/devlopr-jekyll#31]
When i run the site locally it only showed the plain html, it can't import the css and some other files. It seems that it imports all the `/assets/*` from the `root url` instead of `relative_url`, since i have my site not on the root of the domain but in some other repo but it can't load the `/assets/*` files, even when i set the baseurl variable in `_config.yml` file. I searched for the `/assets/css/main.css` in the repo and could find many places where href is directly given as `/assets/css/main.css` instead of with `| relative_url`
The screenshot of the output of the running the server is attached herewith for you to look into:

![Screenshot from 2020-05-20 17-16-47](https://user-images.githubusercontent.com/45457947/82442504-6b6ca480-9abd-11ea-912f-53f907437beb.png)

**Comment by sujaykundu777** [comment]
Sure, the baseurl is not getting attached. Will check this. You can try replacing the head links {{site.url}}/{{site.baseurl}}/assets/ and configure the base url in _config.yml

**Comment by Raghwendra-Dey** [comment]
![Screenshot from 2020-05-25 11-43-01](https://user-images.githubusercontent.com/45457947/82783761-bfd8a100-9e7c-11ea-8767-fdc449011059.png)
These asstes are still not getting loaded. I tried searching for them in the repo and replacing them with the required `path` but even after replacing them its still not able to load them.

**Comment by sujaykundu777** [comment]
Can you share me your config.yml and repo url

**Comment by Raghwendra-Dey** [comment]
I cloned your repo only and just put the `baseurl` argument in the `_config.yml` file, rest everthing is same as your repo.

**Comment by sujaykundu777** [comment]
can you share me the baseurl and url that you have set in _config.yml file.
Just want to check why its not working. coz its working fine for me

**Comment by Raghwendra-Dey** [comment]
Sure, here's my `_config.yml` file screenshot:

![Screenshot from 2020-05-25 19-15-00](https://user-images.githubusercontent.com/45457947/82818224-03063480-9ebc-11ea-9e6b-cede20975960.png)

Lines `6` and `7` are the only lines which i changed, everything else is exactly same.
When i served this locally it showed me this:

![Screenshot from 2020-05-25 19-28-21](https://user-images.githubusercontent.com/45457947/82819398-f387eb00-9ebd-11ea-92c5-b05c3edfc46b.png)
![Screenshot from 2020-05-25 19-29-36](https://user-images.githubusercontent.com/45457947/82819404-f5ea4500-9ebd-11ea-88d6-f1c446b6d0bb.png)

Then i tried searching for the missing `/assets/img/post..` in the repo i found it only in here(line 13):

![Screenshot from 2020-05-25 19-27-56](https://user-images.githubusercontent.com/45457947/82819565-334ed280-9ebe-11ea-80c3-f245dd05d0b3.png)

I replaced it with appending `{{site.baseurl}}` but it only corrected one thing, i.e. output after that is:

![Screenshot from 2020-05-25 19-30-18](https://user-images.githubusercontent.com/45457947/82819703-7315ba00-9ebe-11ea-8841-96b03a2e3b27.png)
![Screenshot from 2020-05-25 19-29-36](https://user-images.githubusercontent.com/45457947/82819698-714bf680-9ebe-11ea-8f77-5b95a2a3c760.png)
