### ISSUE TITLE
[Enhance] Remove social network icons and newsletters

### ISSUE THREAD

**Issue by damdamo** [sujaykundu777/devlopr-jekyll#4]
Hello,

First of all thanks for this great template ! I like it !
I personalize it for my own usage and I saw that I can't remove social networks that I don't use.
For instance, I don't want to insert my Facebook or Twitter.
However, the only way I found to access it is to recreate the *header.html* and remove corresponding fields.
Same remark for newsletters, because I just don't want to use this feature. So, I modified the *footer.html*.

It will be great to have a way to remove it easily.
For example, in the *_config.yml* file, if I comment *twitter_username*, I don't want it to appear on the website.

**Comment by sujaykundu777** [comment]
Sure @damdamo  I will fix that asap :D

**Comment by damdamo** [comment]
Thanks ! 👍

**Comment by sujaykundu777** [comment]
Hey @damdamo. Now you can select and configure which social icons to use easily via editing the config.yml file
