### ISSUE TITLE
long loading page

### ISSUE THREAD

**Issue by russdreamer** [sujaykundu777/devlopr-jekyll#41]
You have a problem, that in head.html from line 152 to line 170 you have a script that trying to get embed.js from unresponsive resource:
`js.src = "https://makerwidget.com/js/embed.js";` 
It waits for a long time, page shown as loading until we got no response.
I didn't make pull request because I don't know why do you load this dynamically.
Two solutions:
1) load it async (but anyway it will fall down with no response)
2) put embed.js into the folder, put this code into head.html 
`<script id="dhm" src="../embed.js"></script>` 
and then change that script on line 152 to this one:
```
<script>
    (function(d, h, m) {
      let js = d.getElementById(m);
      js.onload = function() {
        window.makerWidgetComInit({
          position: "left",
          widget: "ofeeof264otl2l5g-zspk40eq2gaomj2n-higi2qphmveubksi"
        });
      };
    })(document, "script", "dhm");
  </script>
```
But I have no idea what `window.makerWidgetComInit` is doing in this way. Maybe it's useless in this case. That is why I decided to open an issue instead of pull request

**Comment by sujaykundu777** [comment]
That's a script that everyone can remove. It's the makerwidget. It's only for the demo.
