### ISSUE TITLE
[Enhance] Align blog posts

### ISSUE THREAD

**Issue by damdamo** [sujaykundu777/devlopr-jekyll#5]
Hi,

It will be great if we can align the text in markdown.
I was looking for a way to align the text in markdown and I found [this](https://stackoverflow.com/questions/35077507/how-to-right-align-and-justify-align-in-markdown).

However, when I tested to add `<div style="text-align: justify"> your-text-here </div>
`, it breaks all the format.

Do you have a method to do that ?

**Comment by sujaykundu777** [comment]
Hey @damdamo you can use custom css to modify style in the custom-syle.css
