### ISSUE TITLE
algolia search api error

### ISSUE THREAD

**Issue by DarthLykos** [sujaykundu777/devlopr-jekyll#52]
When I try to search any article on blog, the search bar doesn't work.

1. Go to "search page".
2. Use the bar to type any word.
3. Press enter.
4. it "search" but no here so you see nothing.

I made a local copy, edit the api and other things and didn't undestand was happening, never worked.

Why doesn't work if everything have a good config?

**Comment by sujaykundu777** [comment]
Yeah Algolia search needs to be updated. Will write a article explaining on how to setup and index posts.👍🏻

**Comment by DarthLykos** [comment]
That will be nice.

I'll already did it but appear all pages, even shop, gallery and others... I don't know how to remove them. Sorry if you can understand me so good, english is no my native language.

**Comment by sujaykundu777** [comment]
@DarthLykos  you can refer to this article on how to update your search https://sujaykundu.com/jekyll/2020/06/18/how-to-add-realtime-search-to-your-devlopr-jekyll-blog-using-jekyll-algolia/

**Comment by manna018** [comment]
Since I am a noob i removed algolia and I used Simple Search 
Liquid builds a json file
I search into that file from UI

**Comment by sujaykundu777** [comment]
updated search - removed algolia !
