### ISSUE TITLE
bug in post images

### ISSUE THREAD

**Issue by JLykos** [sujaykundu777/devlopr-jekyll#56]
1. Write a post.
2. Insert any image.
3. Publish.
4. Adjust the window to different sizes.
5. See images out of box

**Expected behavior**
Images with auto adjustment according to window size

**Desktop (please complete the following information):**
 - OS: Ubuntu-20.04
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - OS: Android-5
 - Browser: Chrome

**Comment by sujaykundu777** [comment]
Hi you can use this {:class="img-fluid"} after a image to make it responsive in markdown

**Comment by JLykos** [comment]
Also, we can add { .video_container} to make the video responsive (both classes aftes markdown)

**Comment by sujaykundu777** [comment]
@sujaykundu777  you can do something like this ![image-title-here](/path/to/image.jpg){:class="img-responsive"}
