### ISSUE TITLE
Images don't slide (Gallery)

### ISSUE THREAD

**Issue by JLykos** [sujaykundu777/devlopr-jekyll#58]
**Describe the bug**
When you try to see next or previous images on gallery section, nothing happens.

**To Reproduce**
1. Go to Gallery page.
2. See any group of images.
3. Open a imagen from the options
4. Click on next or previus arrow

**Expected behavior**
A slide of pictures from gallery.

**Desktop:**
 - OS: Ubuntu-20.04
 - Browser: Firefox

**Smartphone:** No testing

**Comment by sujaykundu777** [comment]
Hi @JLykos , this seems to work fine,any scenario that you faced when it doesn't work? Can you share the link of the gallery

**Comment by JLykos** [comment]
It's better if you see by yourself, here is the [link](https://jlykos.github.io/gallery/#/) of gallery.

**Comment by sujaykundu777** [comment]
Can you check this gallery in comparison to this devlopr.netlify.com/gallery

**Comment by JLykos** [comment]
> Can you check this gallery in comparison to this devlopr.netlify.com/gallery

I already check it, your gallery can change picture when push on right/left arrow but [here](https://jlykos.github.io/gallery) it doesn't happen
