### ISSUE TITLE
ghostHunter needs rename

### ISSUE THREAD

**Issue by sp33dsk8** [sujaykundu777/devlopr-jekyll#70]
**Describe the bug**
Fix ghostHunter directory capitalization in 'assets/bower_components/ghosthunter' to correctly reference 'ghostHunter' directory with a capital H in hunter.
ex: assets/bower_components/ghostHunter

Else:
[2020-09-25 15:39:29] ERROR `/assets/bower_components/ghostHunter/dist/jquery.ghostHunter.min.js' not found.

**Comment by jackneer** [comment]
May I help with this? thanks!

**Comment by sujaykundu777** [comment]
Issue is fixed.
