### ISSUE TITLE
Add Mathjax Support

### ISSUE THREAD

**Issue by sujaykundu777** [sujaykundu777/devlopr-jekyll#74]
**Why Mathjax**
Currently when adding Formulas or anything related to Syntax, need to be parsed in Mathjax. Many Data Scientists and Developers using this formulas are facing issues, that can be fixed using Mathjax.

**Describe the solution you'd like**
Integrate Mathjax to support Formulas or Equations like -> Sd = sqrt ( sigma ( x-xbar)**2/n) 

**Refer**
For more details you can refer the following:
         https://www.mathjax.org/
         https://en.wikibooks.org/wiki/LaTeX/Mathematics
         http://blog.lostinmyterminal.com/webpages/2015/01/09/math-support-in-jekyll.html

**Comment by preeti13456** [comment]
Please assign this to me

**Comment by preeti13456** [comment]
I have done with the issue only left with bar hex code in part Xbar which I  couldn't able to find will I push my HTML script?

**Comment by preeti13456** [comment]
Not able to push the script to the repo getting error :remote: Permission to sujaykundu777/devlopr-jekyll.git denied to preeti13456.
fatal: unable to access 'https://github.com/sujaykundu777/devlopr-jekyll.git/': The requested URL returned error: 403. Cns you pls check from your side??

**Comment by sujaykundu777** [comment]
@preeti13456  Please raise a PR for the Issue

**Comment by preeti13456** [comment]
What about this issue?

**Comment by preeti13456** [comment]
Sure

**Comment by preeti13456** [comment]
Forked and pushed the PR. Kindly check and let me know

**Comment by sujaykundu777** [comment]
@preeti13456  Just 1 step more, push the changes to your repo :  https://github.com/preeti13456/devlopr-jekyll from there raise a Pull Request to this repo.

**Comment by preeti13456** [comment]
I have done that only  after forking it

**Comment by sujaykundu777** [comment]
@preeti13456 Can you share me the PR link

**Comment by preeti13456** [comment]
https://github.com/preeti13456/devlopr-jekyll

**Comment by sujaykundu777** [comment]
> https://github.com/preeti13456/devlopr-jekyll

This is the repo link. PR looks something like this https://github.com/sujaykundu777/devlopr-jekyll/pull/72

**Comment by preeti13456** [comment]
Yes I'll try to push the file again.
