### ISSUE TITLE
multiple categories

### ISSUE THREAD

**Issue by JorrhukMB** [sujaykundu777/devlopr-jekyll#84]
Is it possible to add a post in multiple categories?

**Comment by sujaykundu777** [comment]
Yes, You need to create a array of categories in your posts yaml 

categories: ['cat1','cat2','cat3']

**Comment by JorrhukMB** [comment]
Oh thanks, appreciated.

**Comment by sujaykundu777** [comment]
Hi @JorrhukMB  I have created a new tutorial for this issue. Here is the [link]( https://devlopr.netlify.app/blog/adding-categories-tags-in-posts/#/).

Hope it helps ! Cheers
