### ISSUE TITLE
Import to forestry.io fails

### ISSUE THREAD

**Issue by denar90** [sujaykundu777/devlopr-jekyll#97]
Howdy 👋 
I have an issue importing theme into Forestry.io.

1. Fork https://github.com/sujaykundu777/devlopr-jekyll
1. Go to 'https://app.forestry.io/dashboard/#/add-site'
2. Select Jekyll
3. Choose forked repo
4. Import fails

Assume it happens because of change (https://github.com/sujaykundu777/devlopr-jekyll/commit/adf939169e48a44738bd2e7723e3bdbca8875151) inside `.forestry/settings.yml`
which makes yml invalid because of brackets `{{`

Is there any chance we can remove `{{` ?
Thanks 😃

**Comment by sujaykundu777** [comment]
@denar90  Thanks for reporting, will have a check and release a fix. 👍

**Comment by denar90** [comment]
Are you interested in PR or is it something you need to test for special use cases?

**Comment by sujaykundu777** [comment]
@denar90  uh ! not getting much time to look to this. Maybe this weekend for sure !

**Comment by sujaykundu777** [comment]
Fixed #99 @denar90  👍

**Comment by sujaykundu777** [comment]
Issue fixed.
